### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Vasanthkvr** [Omenia/robotframework-whitelibrary#10]
Hi,

I started to use the robotframework-whitelibrary.
Will the group support for the open issues.
How to get the details about the team who are actively using the library.

**Comment by AnttiPohjonen** [comment]
Hi

Developers will support with open technical issues when they have time from other projects.
Examples and usage you can look from library´s tests. 

Whitelibrary is still under construction, many helping features still planned for future.

BR,
-Antti

**Comment by Vasanthkvr** [comment]
Thanks
