### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by Vasanthkvr** [Omenia/robotframework-whitelibrary#11]
Hi,

I started to use robotframework-whitelibrary. But i have the performance issue while execute the below steps from the Robot framework.

I have grid control/Table with minimum of 200 Records. I have to iterate all the records each and every iteration.
**Reproduce Steps:**
Step 1 : I attach my existing application 
Step 2: I used to find the table from the Automation Root element from separate project (Using UIAComWrapper). I haven't used the Teststack White API (It's not using the UIAComWrapper).

**ISSUE:**
Time Taken to findAll 200 Records ~40Sec. If i execute the Step 1 and Step 2 from Robot framework.
Time Taken to findAll 200 Records ~1Sec. If i execute the Step 2 at first and then Step 1 from Robot framework

Note: The issue is not only to the attach the existing application. Even at the launch of the new application.

**Comment by IsNoGood** [comment]
Not enough information
