### ISSUE TITLE
Add possibility to set custom screenshot directory

### ISSUE THREAD

**Issue by MichielYKamp** [Omenia/robotframework-whitelibrary#117]
Currently, screenshots taken by WhiteLibrary are stored in the Robot Framework output folder.
But I would like to be able to change this location when loading the library or via a new keyword **`Set Screenshot Directory`**

When loading:
**`Library  WhiteLibrary  screenshot_directory=${OUTPUT_DIR}/Screens`**

Via keyword:
**`Set Screenshot Directory  ${OUTPUT_DIR}/Screens`**

This possibility is available in most other Robot framework libraries like the built-in `Screenshot` library and `SeleniumLibrary`.

**Comment by eeter** [comment]
The new library argument and keyword `Set Screenshot Directory` will be available in stable version 1.5.0. The latest pre-release version also contains the feature if you want to already try it out: pip install -U --pre robotframework-whitelibrary
