### ISSUE TITLE
Keyword Documentation for item enabled/disabled

### ISSUE THREAD

**Issue by bzeug7** [Omenia/robotframework-whitelibrary#119]
**Describe the bug**
Documentation is missing for the following keywords:
Item Should Be Enabled
Item Should Be Disabled

**To Reproduce**
see documentation

**Expected behavior**
N/A

**Screenshots**
N/A

**Comment by eeter** [comment]
Thank you for reporting! The keyword documentation was not generated correctly and has been updated in the repository. However there is still some issue with publishing the page. 

Meanwhile, if you want to browse the keyword documentation and you have the new version installed, the keyword documentation can be generated locally with:
```
python -m robot.libdoc WhiteLibrary keywords.html
```

**Comment by eeter** [comment]
The issue has now been fixed and the up-to-date keyword documentation can be found in http://omenia.github.io/robotframework-whitelibrary/keywords.html
