### ISSUE TITLE
Right Mouse Button Up and Down Key

### ISSUE THREAD

**Issue by bzeug7** [Omenia/robotframework-whitelibrary#132]
**Is your feature request related to a problem? Please describe.**
Currently Left Mouse Button Down and Up keywords exist, but no similar functionality for the right mouse button exists.

**Describe the solution you'd like**
2 new keywords: Right Mouse Button Down and Right Mouse Button Up

**Describe alternatives you've considered**

**Additional context**
I need to be able to simulate a right click-and-drag

**Comment by eeromakiesko** [comment]
Unfortunately the currently delivered version of the underlying WhiteStack these RightDown/RightUp have not been implemented. Thus there is nothing really we do about this issue for now.

**Comment by rasjani** [comment]
As a side not, whitestack does have the implementation but there is no binary releases available.  Working on getting a bit more recent binary releases done just for our package (since we ship them anyway with the lib)
