### ISSUE TITLE
Press keys doesn't work

### ISSUE THREAD

**Issue by MichielYKamp** [Omenia/robotframework-whitelibrary#135]
**Describe the bug**
Keyword `press keys` doesn't work

**To Reproduce**
When I try to use the keyword press keys to simply send a string to the focus

`Press keys  Test string`

I get the following error

`AttributeError: 'NoneType' object has no attribute 'Keyboard'`

**Comment by rasjani** [comment]
While this is a old issue already, this feels more like issue on your side. Code in question uses "Keyboard" property of currently selected window: https://github.com/Omenia/robotframework-whitelibrary/blob/master/src/WhiteLibrary/keywords/keyboard.py#L67

If you have not selected the window, its value is None, and resulting into what you see. 

Im closing this bug for now but do reopen or comment if you are facing the issue after ensuring that you have proper state in the test code either by  using appropriate keywords like `Attach Window` or `Select Modal Window`
