### ISSUE TITLE
'NoneType' object has no attribute 'Get' error while input text.

### ISSUE THREAD

**Issue by NainaDhiman** [Omenia/robotframework-whitelibrary#137]
Hi, 
My code is as below:

Start Application
    Launch Application   ${TEST APPLICATION}
    Sleep  20s

     Attach Application By Name  ssd
     log  done
     ${btoonOK}=  Get Item  text:OK
     Input Text To Textbox   ${btoonOK}   nd

Instead of entering in the text box, m getting error as below:
AttributeError: 'NoneType' object has no attribute 'Get'

Pls advise.

**Comment by AnttiPohjonen** [comment]
Hi

The test flow is missing a "Attach Window" keyword, http://omenia.github.io/robotframework-whitelibrary/keywords.html#Attach%20Window

Please, see also Workflow example in library documentation.

BR,
Antti

**Comment by AnttiPohjonen** [comment]
Closed due no response in a week.

**Comment by AnttiPohjonen** [comment]
Closed due no response in a week.
