### ISSUE TITLE
Running WhiteLibrary via jython

### ISSUE THREAD

**Issue by AnnneN** [Omenia/robotframework-whitelibrary#151]
Hi ,

I have one query:

I have existing robot framework code which is running on jython(jybot.exe), now I want to use white lib in it but its giving me error.
No library found.
I think it is because when i installed white, it got installed in python27 folder and packages are present there not in jyhton. 
I tried manually installing by pointing to jython folder but again it got installed in pyhton folder.
Can you guys help?

Note: I have to use jython for running as there is another lib which is compatible in that format.

**Comment by rasjani** [comment]
Teststack.white real implementation is written in C# and we use python .net as middleware to interact with it.  While our code most likely could run on Jython, .net layer requires CPython.   Only way around to have your Jython and still be able to use white, you must use robot frameworks’ remote interface.  However even in that case, you still need to have cpython installed..

**Comment by rasjani** [comment]
https://github.com/robotframework/RemoteInterface/blob/master/README.rst
