### ISSUE TITLE
Python 3.8 pip install error

### ISSUE THREAD

**Issue by y2j44** [Omenia/robotframework-whitelibrary#173]
Hey Sorry. I didn;t see any issues up here regarding python 3.8

I have a coworker that was trying to install robotframework-whitelibrary on python 3.8-

 32 bit and received an error. see attachment

**Comment by rasjani** [comment]
AFAIK pythonnet which is used as a bridge from python code to calling teststack white  dll's does not support 3.8 (and even support for 3.7 has been a very recent addition). So, essentially there is nothing much we can do to support higher than 3.7 ..

**Comment by rasjani** [comment]
No attachment of the logs and since pythonnet isnt supported on python 3.8, im closing this ticket.
