### ISSUE TITLE
NameError: global name 'PY2' is not defined

### ISSUE THREAD

**Issue by hleskien** [Omenia/robotframework-whitelibrary#34]
Hi,

does this library depend on Python 3.x or am I missing some module(s)?

```
  File "[...]\python-2.7.15\lib\site-packages\WhiteLibrary\WhiteLibrary.py", line 454, in _log_directory
    return os.getcwdu() if PY2 else os.getcwd()
NameError: global name 'PY2' is not defined
```

Thank you and kind regards

Holger

**Comment by Kompakti** [comment]
This library does not depend on Python 3.x. The PY2 definition was missing and we had not tested in a situation which would raise RobotNotRunningError (PY2 is referenced only in that case).
Thanks for reporting, fix should be merged soon.

**Comment by hleskien** [comment]
Thank you, it works now!
