### ISSUE TITLE
Error installing via pip, no such file or directory: requirements.txt

### ISSUE THREAD

**Issue by jerry57** [Omenia/robotframework-whitelibrary#54]
**Describe the bug**
Attempting to install via pip

getting the following error about requirements.txt not existing

pip install -U robotframework-whitelibrary
Collecting robotframework-whitelibrary
  Using cached https://files.pythonhosted.org/packages/ad/b5/cadcac69224c6b4c89144f850e22a5dbef81e12dcb731635788c46b6dce4/robotframework-whitelibrary-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jschne~1\appdata\local\temp\pip-install-fehdrm\robotframework-whitelibrary\setup.py", line 9, in <module>
        with open("requirements.txt", "r") as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\jschne~1\appdata\local\temp\pip-install-fehdrm\robotframework-whitelibrary\

Using python 2.7.14
RF 3.0.4
Windows 10

**Comment by rasjani** [comment]
And fix should now also be released in version 1.1.1 in pypi.. Hopefully it works, i dont have windows handy to try it out atm..

**Comment by jerry57** [comment]
Yes, now fixed in v1.1.1  Please go ahead and close this issue.
