### ISSUE TITLE
unable to attach to "New Mail" window of outlook

### ISSUE THREAD

**Issue by lingarajrise** [Omenia/robotframework-whitelibrary#73]
**Describe the bug**
I am trying to automate outlook using robot white library. when i click new Mail , I am unble to attach to new mail winowd

**To Reproduce**
Launch application outlook
attach outlook windows
open new mail windows 
try to attach to new mail

code 
----
outlook test 
           Launch Application                  outlook.exe
           sleep                               15
           attach window                       *******************
           Click item                          text=New Email
           #Attach Application By Name          OUTLOOK
           attach window                       Untitled - Message (HTML)
           Click item                          text=To...
           
Below is the exception
-------------------------
AutomationException: Couldn't find window with title Untitled - Message (HTML) in process 19264, after waiting for 30 seconds
   at TestStack.White.Factory.ChildWindowFactory.WaitTillFound(Func`1 find, String message)
   at TestStack.White.Factory.WindowFactory.CreateWindow(String title, Process process, InitializeOption option, WindowSession windowSession)
   at TestStack.White.Application.GetWindow(String title, InitializeOption option)
   at TestStack.White.Application.GetWindow(String title)

**Comment by eeter** [comment]
Hi,

I would first use an inspector tool to check if there are e.g. extra spaces between words or trailing spaces in the window title. If so, they should be included in the parameter value. In the current library version, the window must be attached using the exact title of the window.

**Comment by niinakr** [comment]
I had the same problem. This solution works for me:

Launch Application
Attach Application By Id
Attach Window
Click item

**Comment by eeter** [comment]
Was this problem solved, can the issue be closed?

**Comment by eeter** [comment]
Closing the issue due to inactivity.
