### ISSUE TITLE
Not abe to access any keywords of whitelibrary after installing

### ISSUE THREAD

**Issue by dhingrachirag** [Omenia/robotframework-whitelibrary#88]
**Describe the bug**
I installed Robot  framework - white library  and it successfully installed but when i am trying to access white library in robot script , i am not able to use any keyword .I am using pycharm as my development environment.I tried with launch application and it threw me error:

No keyword with name 'LAUNCH APPLICATION' found.

**Expected behavior**
It should call the keyword after installing whitelibrary

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Please acknowledge as i am not able to call even single keyword in whitelibrary

**Comment by eeter** [comment]
Please provide more information:
- What version of the library is installed? (pip show robotframework-whitelibrary)
- How do you import the library in your tests?

**Comment by eeter** [comment]
Are there errors in the beginning of the log.html file generated from your test run?

**Comment by dhingrachirag** [comment]
No spaces are correct only, still i am not able to access whitelibrary.The only error what i get is No keyword with name 'LAUNCH APPLICATION' found.

**Comment by eeter** [comment]
Without more details it is hard to say what is causing this. When there is an error with library import, there is usually some error shown in the log.html, under "Test Execution Errors" (open log in browser).

**Comment by eeter** [comment]
Is this problem still occurring?

**Comment by eeter** [comment]
Closing the issue due to inactivity.

**Comment by krishnagkashyap** [comment]
facing the same issue on 1.6.0 version which latest as well.
